[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm run build"
watchPatterns = ["backend/**"]

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
